# Permalinks
permalink: pretty

# Setup
title: Publog
tagline: Developer Blog of Shivishbrahma
url: http://shivishbrahma.github.io/publog
paginate: 1
baseurl: '/publog'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
    sass_dir: _sass
    style: :compressed

# Set tags
collections:
    tags:
        output: true
        permalink: /tags/:path/
        sort_order:
            - published
            - title
    posts:
        output: true
        sort_order: date
        sort_reverse: true

# About/contact
author:
    name: Purbayan Chowdhury
    url: https://twitter.com/shivishbrahma
    email: pur.cho.99@gmail.com

# Custom vars
version: 0.1.0
github:
    repo: https://github.com/shivishbrahma/publog

# Gems
gems:
    - jekyll-paginate
    - jekyll-gist

plugins:
    - jekyll-paginate
    - jekyll-gist

